version: '3.8'

x-healthcheck-default:
  &healthcheck-default
  interval: ${HEALTH_INTERVAL}
  timeout: ${HEALTH_TIMEOUT}
  retries: ${HEALTH_RETRIES}
  start_period: ${HEALTH_START_PERIOD}
  start_interval: ${HEALTH_START_INTERVAL}
x-servicea:
  &servicea
  image: ${NGINX_IMAGE}
  healthcheck:
    << : *healthcheck-default
    test: ["CMD", "curl", "", 
      "http://localhost:${SERVICEA_INTERNAL_PORT}"]

services:
  servicea1:
    << : *servicea
    container_name: servicea1
    ports:
      - "${SERVICEA1_EXTERNAL_PORT}:${SERVICEA_INTERNAL_PORT}"
    volumes:
      - ./servicea1:/usr/share/nginx/html
  servicea2:
    << : *servicea
    container_name: servicea2
    ports:
      - "${SERVICEA2_EXTERNAL_PORT}:${SERVICEA_INTERNAL_PORT}"
    volumes:
      - ./servicea2:/usr/share/nginx/html
  knoxgw:
    container_name: knoxgw
    image: knoxgw
    build:
      context: ./knoxgw
      dockerfile: ./Dockerfile
      args:
        - knox_release_mirror=${KNOX_RELEASE_MIRROR}
        - knox_version=${KNOX_VERSION}
        - knox_user_group=${KNOX_USER_GROUP}
        - knox_user=${KNOX_USER}
        - knox_admin_user=${KNOX_ADMIN_USER}
    ports:
        - "${KNOX_EXTERNAL_PORT}:${KNOX_INTERNAL_PORT}"
    depends_on:
      - servicea1
      - servicea2
    #curl -ku admin:admin-password https://localhost:8445/gateway/manager/admin-ui/
    #curl -kf https://localhost:8445/gateway/manager/admin-ui
    #curl -ku admin:admin-password https://localhost:8445/gateway/anyservice/servicea/index.html
    healthcheck:
        << : *healthcheck-default
        test: ["CMD", "curl", "-ku admin:admin-password", 
          "https://localhost:${KNOX_INTERNAL_PORT}/gateway/anyservice/servicea/index.html"]